import './src/App';
import './src/index.js';
import './src/firebase';
import './src/components/About/index.js';
import './src/components/AnimatedLetters/index.js';
import './src/components/Contact/index.js';
import './src/components/Dashboard/home.js';
import './src/components/Dashboard/index.js';
import './src/components/Home/Logo/index.js';
import './src/components/Home/index.js';
import './src/components/Layout/index.js';
import './src/components/Login/index.js';
import './src/components/Portfolio/index.js';
import './src/components/Sidebar/index.js';
import './src/components/Skills/index.js';
// CSS Files
import './src/index.css';
import './src/App.scss';
import './src/components/About/index.scss ';
import './src/components/AnimatedLetters/index.scss ';
import './src/components/Contact/index.scss ';
import './src/components/Dashboard/home.scss ';
import './src/components/Dashboard/index.scss ';
import './src/components/Home/Logo/index.scss ';
import './src/components/Home/index.scss ';
import './src/components/Layout/index.scss ';
import './src/components/Login/index.scss ';
import './src/components/Portfolio/index.scss ';
import './src/components/Sidebar/index.scss ';
import './src/components/Skills/index.scss ';